### ISSUE TITLE
男は黙ってjQuery 3.0

### ISSUE THREAD

**Issue by gaogao-9** [potato4d/potato4d#1]
jQuery 3.0はいいぞ
https://blog.jquery.com/2016/05/20/jquery-3-0-release-candidate-released/

**Comment by potato4d** [comment]
要介護の世界から抜けてきたから使っても良さそうですけど、
そろそろ要介護な世界は滅んだんですかね

**Comment by potato4d** [comment]
現状としては正式版出たら使うスタンスです

**Comment by gaogao-9** [comment]
正式版が出たのでreopenしました

[jQuery 3.0 Final Released!](https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/)

**Comment by potato4d** [comment]
とりあえず変更点とか一通り目を通したけれど、
まだXHRをPromiseで書いてみてない（というか今機会がない）のでそれやったらDone。

**Comment by potato4d** [comment]
Done.
