### ISSUE TITLE
Sketchでモブプログラミング的なことをするイベントをやる

### ISSUE THREAD

**Issue by lightnet328** [potato4d/potato4d#102]
> Sketchのやっていきの本が欲しい
> https://twitter.com/lightnet328/status/936890662317731842

> Sketch入門！みたいな奴じゃなくて実際にアプリの画面をどうやってどこまで設計していくかみたいなやつ
> https://twitter.com/lightnet328/status/936890914949050368

> なんかモブプログラミング的な感じでエンジニアでSketch触ってる人間とSketchで作り慣れている人間でやるやつやりたくない？
> https://twitter.com/potato4d/status/936891060701224961

> やりたいやりたい
> https://twitter.com/lightnet328/status/936891258143830016

**Comment by p1ch-jp** [comment]
趣旨理解太郎
