### ISSUE TITLE
そろそろご飯食べたらどうですか

### ISSUE THREAD

**Issue by Petitsurume** [potato4d/potato4d#11]
https://github.com/potato4d/today-meshi

**Comment by p1ch-jp** [comment]
むしろ、絶食でギネスを目指しませんか？

**Comment by potato4d** [comment]
ライフログアプリMeshiRecorderがいつまでたっても未完成なのでまだ食事を許されません。

**Comment by hinaloe** [comment]
絶食なのに @p1ch-jp  に🍣集ってるとは一体……

**Comment by p1ch-jp** [comment]
証拠写真撮っちゃうんだから...

**Comment by potato4d** [comment]
たべました

**Comment by hinaloe** [comment]
MeshiRecorderできたってこと？

**Comment by Petitsurume** [comment]
MeshiRecorderをOSSにするべきでは？

**Comment by hinaloe** [comment]
そういやMeshiRecorderはOSSになるって聞いてたような

**Comment by potato4d** [comment]
食べたのでとりあえず一旦しめるね
