### ISSUE TITLE
WebサイトをAPI化するプログラムの開発

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#15]

**Comment by Petitsurume** [comment]
YQLみたいな奴？

**Comment by potato4d** [comment]
Kimonoが死んだので、アレっぽいのを作りたいなぁと漠然と思ってる

**Comment by potato4d** [comment]
https://speakerdeck.com/potato4d/node-dot-jsdewebsaitokaraapiwozuo-rupuroguramuwoshu-itahua

**Comment by p1ch-jp** [comment]
コントリビュート求むって書いてあるのに、リポジトリが無い気がします？

**Comment by potato4d** [comment]
まだpublicになってないかんじなんすよねー

**Comment by p1ch-jp** [comment]
そのうち公開されるですか？

**Comment by potato4d** [comment]
うん

**Comment by p1ch-jp** [comment]
楽しみにしてます😊

**Comment by potato4d** [comment]
結局あげられてないしだめっぽい感じがある
