### ISSUE TITLE
Owl8とオフ会

### ISSUE THREAD

**Issue by Owl8** [potato4d/potato4d#22]
なかなか予定が立たない

**Comment by potato4d** [comment]
関西勢オフ in Tokyoになるのもネタでいいけど折角近いんだしサクッとオフってみたいよね

**Comment by Owl8** [comment]
今週の土曜まで東京いるしその帰りに大阪ワンチャンある

**Comment by Himanoa** [comment]
ぱくとまの金で焼き肉関係ないでショ！

**Comment by potato4d** [comment]
@Owl8
今週土日WordCampのスタッフやわ……
https://2016.kansai.wordcamp.org

**Comment by potato4d** [comment]
@Owl8 
Choose
* 8/11     Potato4dが明石高専に来る
* 8/18〜 owlが大阪に来る
* 未来    @pakutoma のおごりで焼き肉

**Comment by Owl8** [comment]
8月の予定はまだちょっと厳しいかもしれない

**Comment by potato4d** [comment]
ごめん間違えた7月だわ

**Comment by Owl8** [comment]
・8/18に4dが明石高専に来る
はないんですか

**Comment by potato4d** [comment]
なさそう

**Comment by Owl8** [comment]
8/13までの土日でそっちの都合がつく日がいいと思う

**Comment by potato4d** [comment]
8/6に無限にふるよにやったのでこのIssueはオアｗり！
