### ISSUE TITLE
全く気付かないうちにPotato4d.meのIssueが集まってくるIssue

### ISSUE THREAD

**Issue by hinaloe** [potato4d/potato4d#23]

**Comment by potato4d** [comment]
このIssueでよくない？

**Comment by hinaloe** [comment]
ステータス見失いやすくならない？（

**Comment by potato4d** [comment]
そもそもGithub上にないものにIssue建てるって発想がナンセンスだから多少はね

**Comment by hinaloe** [comment]
まぁいいやってことでとりあえず

----

# ギャラリーをスマホでみたとき宇宙
![screenshot_20160705-104135](https://cloud.githubusercontent.com/assets/5253290/16578380/24f12d26-42d5-11e6-8b8e-60ae8b046e6e.png)

**Comment by potato4d** [comment]
そもそもPotato4d.meはGitHubで公開されているわけじゃないから取り扱う気が無いんだよね。
