### ISSUE TITLE
家を決める

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#52]
目標：
年内に家を決める

タスク：
- [x] 相場を知る
- [x] 地域を知る
- [x] 不動産屋を決める
- [x] 日程を決めて内覧に行く
- [x] 申し込む
- [x] オーナーに許可してもらう
- [x] 契約をする

概要：

前回のチャレンジでは
https://github.com/the-house-of-ohnin/issues/issues/3
https://github.com/the-house-of-ohnin/issues/issues/23

というかたちで無念にも惨敗を喫したので、今回こそは勝つぞ！

**Comment by potato4d** [comment]
[WIP]Macに移行してからEsaにかく
必須条件：

* 管理費込みで家賃8万円ぐらいまで(それ以上はつらい)
* 下記に添付する画像の円の範囲内(それ以上だと家賃が3万円のアパートとかじゃないとつらくなる)
* 

<img width="351" alt="21db2ec47c47d54a7292c1cb3b720086" src="https://cloud.githubusercontent.com/assets/6993514/19834404/c5b19b34-9ea0-11e6-8a58-45daa084075b.png">

**Comment by otofune** [comment]
進捗どうですか？

**Comment by potato4d** [comment]
@otofune 
今月半ば、14の週に内覧予定。相場はざっと把握したので、あとは現地で良さげな物件がないか探す感じかなぁ……。

**Comment by potato4d** [comment]
基本的にエリアは千駄ヶ谷もしくは北参道の範囲。
それでも、どうしても千駄ヶ谷周辺で調べると新宿御苑をまたいだその先が出てきたりするので、このへんは多分不動産屋で聞くしか無い。

基本は

* 東京メトロ：北参道エリア徒歩〜10分
* JR中央線   ：千駄ヶ谷エリア徒歩5〜10分程度

で見とくべきかなぁ……

**Comment by p1ch-jp** [comment]
5~8万円とかだと普通に保証人が必要だと思うし、事情を話して保証会社使えるところに絞って探してもらったほうが良いぞい

**Comment by potato4d** [comment]
保証会社のみでOKっぽい物件もなんか多そうな感じあった
ただ条件には入れておくー。

**Comment by potato4d** [comment]
これ「不動産屋を決める」、現地でシュッとした方がいいかな

**Comment by potato4d** [comment]
つい先程不動産屋から「保証会社の審査はOK」との連絡がきました。

**Comment by potato4d** [comment]
今日は連絡がなかった。
月曜にオーナーからもOK連絡がきて、11月中に契約みたいな運びかな。

**Comment by potato4d** [comment]
連絡がきた。審査OKとのことで、契約を進めていくことに。

**Comment by potato4d** [comment]
契約まできたぞ！！！！

**Comment by potato4d** [comment]
見取り図かきました
https://twitter.com/potato4d/status/802894416201400321

**Comment by potato4d** [comment]
ようやく昨日今日で諸々の手続きが終了。後は自分が動くだけだ！
