### ISSUE TITLE
月末までにお金を使いきってしまう

### ISSUE THREAD

**Issue by p1ch-jp** [potato4d/potato4d#6]
そして、お金がないのに他人に寿司を奢らせようとする。
早急に解消して欲しい。

**Comment by potato4d** [comment]
善処します

**Comment by p1ch-jp** [comment]
なんでも仕様で片付けるのはクソエンジニアの特徴だって、近所の猫が申していたのですが、そこら辺についてはどのようにお考えでしょうか？

**Comment by potato4d** [comment]
横から失礼します。

まさかとは思いますが、この「近所の猫」とは、あなたの想像上の存在に過ぎないのではないでしょうか。

あなたの病気は悪化しています。

あり得ません。専門家の意見を聞くまでもないことです。

**Comment by p1ch-jp** [comment]
正面から失礼してください。
リポジトリの説明にて、俺へのIssueはここに立てろと書いてあったので立てました。
あなたは横からではなく正面からこのIssueに向き合うべきではないでしょうか？
近所の猫に関しては私の想像上の存在です。ややこしい発言をしてしまい、申し訳ありませんでした。
さて、話題を元に戻して、なんでも仕様で片付ける件についてあなたのお考えを聞かせていただければと存じます。よろしくお願いします。
正面から失礼いたしました。

**Comment by potato4d** [comment]
なんでも仕様で片付けるのはクソだと思います。

ただ、今回の場合は適切な挙動が行われておりますので、仕様であることは間違いないかと思います。

**Comment by p1ch-jp** [comment]
仕様ならば仕方がないですね。

ところで、寿司は何曜日の何時からが良いですか？
店は先斗町にある「すしてつ」ってところで良いですかね？
安くて美味しいお寿司が食べられるとはてな社の人に聞いて一度行ってみたいと思っていました。

**Comment by potato4d** [comment]
木曜のよるどうでしょうか？

**Comment by p1ch-jp** [comment]
OKです。

**Comment by potato4d** [comment]
@p1ch-jp 
ちょっと木曜むりかも。
金曜夜でも大丈夫ですか？

**Comment by p1ch-jp** [comment]
@potato4d ちょっと金曜は良いか悪いか怪しいので、後日連絡します。忘れていたら、リマインドよろしくお願いします。

**Comment by p1ch-jp** [comment]
@potato4d 華金、寿司行くぞ:sushi:

**Comment by potato4d** [comment]
寿司という目標が達成されたしこれCloseでいいのかな……

**Comment by p1ch-jp** [comment]
月末になっても金が余ってたらクローズしても良い

**Comment by potato4d** [comment]
月末ならある(ない)

**Comment by potato4d** [comment]
イケるようになったしCloseるか

**Comment by p1ch-jp** [comment]
Closeしても良いと思う

**Comment by potato4d** [comment]
でも敷礼を乗り越えたらがいいかな

**Comment by potato4d** [comment]
とりあえず使いきらずに月末乗り切ったので一旦占めます
