### ISSUE TITLE
ネット回線を敷く

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#61]
家を借りたらネット回線を最強にする

**Comment by potato4d** [comment]
ここ、強い人に色々教えて欲しい

**Comment by otofune** [comment]
au光は良いよ
だけど場所によってNURO光引けそう
ほかは知らない

**Comment by potato4d** [comment]
@otofune 引けるかどうかって聞いてみるしかないんやろか？

**Comment by otofune** [comment]
@potato4d 住所からNURO光のサイトでエリアに入ってるか調べれるよ
https://www.nuro.jp/apply.html?nmrint=srv_apply_web#applyWebFlow

**Comment by potato4d** [comment]
<img width="970" alt="2016-11-26 0 30 52" src="https://cloud.githubusercontent.com/assets/6993514/20629569/a0924766-b36f-11e6-8acb-8b0b66731575.png">

うーん9階建て階建てなんだよなぁ

**Comment by otofune** [comment]
実際のその住居に入れれるかどうかはどうにも…
こればかりは聞いてみるしか無いと思う

**Comment by potato4d** [comment]
@otofune なるほどねありがとう
ちなみにauひかりは何がええのん？

**Comment by otofune** [comment]
@potato4d 
系列を使っている感想として速度が体感落ちたことがないのと、知り合いも速度がしっかり出るらしい (この場合の知り合いはリアルとネット双方)
僕の場合は1Gbps契約で700Mbpsくらいが安定して出る

**Comment by potato4d** [comment]
@otofune めっちゃ強いやん神か？？？

**Comment by otofune** [comment]
@potato4d わかる
NURO光の2GbpsプランはONUの2ポートに1Gbpsずつ振られるらしいんだけど、両方800-900Mbpsくらい出ててもっとつよいという感じ (こちらはリアルの知り合いの話ではない)

**Comment by potato4d** [comment]
なるほどなぁ
NURO対応してるかわからんのと、あとあれ固定IPなかった気がするので、ちょっと対応状況もコミコミで考えたいところ

@otofune 
auやと固定あんのかな

**Comment by otofune** [comment]
@potato4d au光 (au-one net)の場合はDHCPだけど異様に長い (リースが1日くらいっぽい) のであんま変わんないですね
固定IPオプションは無いっぽい…かな [au-oneのオプションサービスページ](http://www.au.kddi.com/internet/auonenet/option/#cont05) を見る限り
au光をパイプとして使ってSo-netとか使えば使えるかも (フレッツ光と同じような感じ、au光はフレッツ光で言うOCNがよく使われてると思ってくれるといいと思う)
あとOB25Pはもちろん含まれてるけどこれは普通のプロバイダなら仕方ないか

**Comment by potato4d** [comment]
@otofune

なるほどねん
まぁIP周りはオンプレでサーバー運用とかやる機会なさそうやしええかなぁ

色々助かります

**Comment by otofune** [comment]
@potato4d 昔インターネット人権なかった人間なので人権を流布していきたい心が強い

**Comment by pakutoma** [comment]
ぽてとは無線生活だろうから無線LANルータも良いの買おうな

**Comment by potato4d** [comment]
@otofune

奇遇やなわしも家の回線変えさせるまでは常時500k〜5mbpsの住人やったで

**Comment by potato4d** [comment]
@pakutoma
Amazonのほしい物リストについかしとくね

**Comment by atnanasi** [comment]
NECのルーターだけは絶対に避けてほしい。
もしレンタルで来ても他のルーター使うほうが絶対にいい

**Comment by otofune** [comment]
ルータASUSのゲーミング向け無線を導入するの良さそう（知見ゼロの意見）
僕は無線ルーターはBuffaloとNECしか使ったことないのであまり大層なことは言えないけどNECはダメ

**Comment by potato4d** [comment]
@atnanashi
NECあかんの

**Comment by otofune** [comment]
@atnanashi ONUがなんと一体型NECウグゥー、PPPoEを外のルーターに任せるのはできそうなのでそれで行くのが一番良さそうかな

**Comment by potato4d** [comment]
昔Atermシリーズがゴミで今のアーオーデータの4000円ぐらいのやつが良かったイメージしかないけどアンテナバリ4本ぐらいのめっちゃ強力なやつ買うか

**Comment by potato4d** [comment]
IDミスったせいでIDミスりの連鎖が発生しててわらう

**Comment by otofune** [comment]
@potato4d うちの前回線何かにつけて100kbps以下に落ちてた

**Comment by potato4d** [comment]
@otofune
なるひど

**Comment by otofune** [comment]
間違えたー！IDミスっちゃった！

アンテナ四本マジで強そうだし良さそう、I-O DATAは悪くないって聞いた、Buffaloは純正ファームの飛びが悪かったけどこれは四年前なので今はわからない

**Comment by potato4d** [comment]
これで良さそうでは
https://www.amazon.co.jp/ASUSTek-600Mbps無線ルーター-Aiprotection-Trendmicro-RT-AC68U/dp/B00GJIEYBI

**Comment by otofune** [comment]
ASUSは良さそう

**Comment by potato4d** [comment]
見た目が強そうなのがBUFFALOとASUSだった

**Comment by pakutoma** [comment]
ASUSのRT-AC68Uは暴力なので圧倒的に良い、金があるならそれ
Atermは(intelと致命的に相性問題が多い以外は)そんなに悪い選択でもないと思うけど、少なくともBuffaloの低価格帯よりは
Buffaloの高価格帯のやつは白い方がおすすめ、黒い方はあまり評判よくない

**Comment by potato4d** [comment]
@pakutoma
暴力ウケた
そうなのか

**Comment by otofune** [comment]
AC-87Uと2千円差なので68U買うなら87U買おうぜ

**Comment by pakutoma** [comment]
87U買うなら88U買おうぜ

**Comment by pakutoma** [comment]
88U買うならCiscoの(ry

**Comment by pakutoma** [comment]
87U後継だしそっちのほうが良いね
68Uって2014年とかでしょ確か

**Comment by potato4d** [comment]
87Uが良いのね

**Comment by otofune** [comment]
Cisco、ネットワークエンジニア目指してなさそうな人間が持つにふさわしいものなのか議論が待たれる
68Uは2013年だった、87Uが2014、88Uが2016らしい

**Comment by otofune** [comment]
88Uだな！（大幅値上げ）

**Comment by potato4d** [comment]
なんかMacのTimeMachineに対応してるとかいう情報があって、より欲しくなってるしこのシリーズで年代だけ決めて書いたいかな

Ciscoはなんか必要性感じないっすね……

**Comment by otofune** [comment]
型落ちでも対して困らなさそうだけど、しばらく使うんだったら最新の、というか新しいの買っとけみたいなのある

**Comment by potato4d** [comment]
スペック表見て違いがほとんどわからなくて「多分他のエンジニアがJavaScriptを見たらこんな感じなんだろうな」みたいな気持ちになった

**Comment by potato4d** [comment]
むっちゃミスってCloseしたし知性がない

**Comment by atnanasi** [comment]
NECのルーターはほんとに基礎的な部分が出来てないから止めたほうがいい
自分のルーターは静的IPマスカレードも動かないしNAT溢れするから外向けはRT107e使ってる

**Comment by pakutoma** [comment]
うちIPマスカレード動くよ…？
プライマリDNSをLAN内にして運用してたら時々引けなくなるから再起動してるけど
牛の低価格帯よりはマシって程度しかないのは確か

**Comment by otofune** [comment]
うちのNECルーターも静的マスカレードは動くよ
NAPTテーブルの有効時間短くするまでパケットがひとつも通らなくなる通信障害が起きることはあった、デフォルトの値が確か3600秒とかになってた

**Comment by potato4d** [comment]
と、取り敢えず俺はどれを買えばいいんだ

**Comment by potato4d** [comment]
手続きやったので待つだけなので終わり（アルゴリズムたいそう）

**Comment by otofune** [comment]
結局どこにしました？

**Comment by sakurapleasure** [comment]
OCNは安定しているからいいぞ

**Comment by potato4d** [comment]
OCN、CDNっぽい

**Comment by potato4d** [comment]
正義が通るっぽい
