### ISSUE TITLE
腕立て伏せしよう

### ISSUE THREAD

**Issue by mismith0227** [potato4d/potato4d#63]

**Comment by potato4d** [comment]
@mismith0227 腕立て伏せが現状一回できるかどうか（腕立て伏せられない）な可能性があるので、もうちょいゆるいところからじゃダメですかね……＞＜

**Comment by potato4d** [comment]
http://qiita.com/masahixixi/items/0b9ecc00e26afd8015c1

**Comment by potato4d** [comment]
今日も腕相撲でたくさん負けた。精進しないと。

**Comment by mismith0227** [comment]
知ってるかもしれんけど貼っておく

筋肉 Advent Calendar 2016
http://qiita.com/advent-calendar/2016/muscle

筋トレを継続する技術
http://qiita.com/modal_soul/items/d6cdbde9072e2e38a609
