### ISSUE TITLE
新生活で必要なものがわからない

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#66]
このままだったらルビーサファイアで秘密の力で開けただけの秘密基地みたいになる

**Comment by p1ch-jp** [comment]
何も無しで生活はじめて、必要なものを買い足していく方式がいいぞ。(ただし初日は布団が無くてバスタオル被って寝る羽目になるから気をつけてな)

**Comment by d-kusk** [comment]
100均で売ってるレンジでパスタ茹でるやつイイヨ
それか電気ケトル 早いし電気代安い

**Comment by potato4d** [comment]
取り敢えず無限に突っ込んで見ていってる
http://www.amazon.co.jp/registry/wishlist/2O15GBGT0GS3Y/ref=cm_sw_r_tw_ws_O5.oybYD1T78Z

ケトル入れてなかったので足そう

**Comment by katabamia** [comment]
料理するならIHの卓上版みたいなやつとかあったほうが良さげな気がする
あとフライパンは安いのを買い直していったほうがコスパがいいぞ
もしキッチンが備え付けであるなら銀色のついたてみたいなアレ買っとこう
あれを置いとくだけで汚れ方がぜんぜん違う

排水口に貼り付けるタイプのゴミ取りシール的なのがあるのでそれ買っとくと掃除がめっちゃ楽

**Comment by katabamia** [comment]
電子レンジと冷蔵庫は最低限必要な感じはある
レンジは別に小さくてもいいけど冷蔵庫は小さいの買うとあとあと後悔するので余裕があるのであればなるべく大きいのを買おう(戒め
