### ISSUE TITLE
CODE HAMMERに出る

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#68]
@mktakuya と共に @lightnet328 を絶対に倒すからな
https://code-hammer.tech-salon.com

**Comment by mktakuya** [comment]
よろしくお願いします〜〜〜！！！
👍 👍 👍

**Comment by potato4d** [comment]
出て参加記録書いたぞ！！！
http://blog.potato4d.me/2016/12/06/hackathon/
http://blog.potato4d.me/2016/12/06/burning-village/
