### ISSUE TITLE
新居祝い忘年会

### ISSUE THREAD

**Issue by potato4d** [potato4d/potato4d#73]
やりたいんだけど

**Comment by potato4d** [comment]
* 北参道駅前の新居
* 12/17(土)もしくは12/18(日)または2日でわけて
* 適当に寿司かピザかなんか頼みながら普通にダベっていく回をやりたい
* 年末だし忘年会も兼ねて

**Comment by otofune** [comment]
:+1: :100: :goat:

**Comment by potato4d** [comment]
立てた
https://connpass.com/event/46728/

**Comment by potato4d** [comment]
やった
