### ISSUE TITLE
[WIP]伝説のまとめをつくる

### ISSUE THREAD

**Issue by p1ch-jp** [potato4d/potato4d#8]
[@potato4d伝説まとめ](http://chiraura.me/potato4d/)という記事を保守・運用するのが面倒くさいです。
こちらのリポジトリにて、たくさんの人の手によって管理されるべきかと思います。
移設をご検討していただけると幸いです。よろしくお願い致します。

**Comment by potato4d** [comment]
[WIP]も付与しておいたほうがよろしいでしょうか？

**Comment by p1ch-jp** [comment]
@potato4d ありがとうございます。
